version: "3.9"
services:
  front:
    build:
      context: .
      dockerfile: ./docker/front.dockerfile
    volumes:
    - ./apps/student-registration:/app/apps/student-registration
    - ./libs/api-interfaces:/app/libs/api-interfaces

    ports:
      - "4200:4200"

  api-gateway:
    build:
      context: .
      dockerfile: ./docker/api-gateway.dockerfile
    volumes:
      - ./apps/api/api-gateway:/app/apps/api/api-gateway
      - ./apps/api/dto:/app/apps/api/dto
    command: sh -c "cd apps/api/api-gateway && yarn start:dev"
    ports:
      - "3000:3000"

  api-student-registration:
    build:
      context: .
      dockerfile: ./docker/student-registration.dockerfile
    volumes:
      - ./apps/api/student-registration:/app/apps/api/student-registration
      - ./apps/api/dto:/app/apps/api/dto
    command: sh -c "cd apps/api/student-registration && yarn start:dev"
    ports:
      - "3001:3000"
